codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    project:
      default:
        enabled: yes
        target: 85%
    patch:
      default:
        enabled: yes
<<<<<<< HEAD
        target: 50%
=======
        target: 80%
>>>>>>> b72a69f (Update dependencies (#20))
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
ignore:
  - "server/manage.py"
  - "server/config"
<<<<<<< HEAD
  - "server/locustfile"
=======
>>>>>>> b72a69f (Update dependencies (#20))
  - "server/**/apps.py"
